#!/usr/bin/perl -wT

use strict;
use CGI;
use Data::Dumper;
use JSON;
use List::Util 'shuffle', 'min', 'max' ;
use POSIX;
use Template;
use XML::Simple;
use lib "lib/";
use NPCGenerator ;
use GenericGenerator;
our $q = CGI->new;


my $testcityid=GenericGenerator::set_seed();
if (defined $q->param('seed')){
    $testcityid=$q->param('seed');
}elsif (defined $q->param('cityid')){
    $testcityid=$q->param('cityid');
}elsif (defined $q->param('continent')){
    $testcityid=$q->param('continent').'00';
}elsif (defined $q->param('region')){
    $testcityid=$q->param('region').'0';
}

my $namegen=NPCGenerator::generate_npc_names(  $q->param('race'),  $q->param('count')   );

if (defined $q->param('type') and $q->param('type') eq 'xml' ){
    print $q->header( 'text/xml' );
    print "<?xml version='1.0'  encoding='ISO-8859-1' ?>\n";
    print XMLout($namegen);
}elsif (defined $q->param('type') and $q->param('type') eq 'json' ){
    print $q->header( 'application/json' );
    my $JSON  = JSON->new->utf8;
    $JSON->convert_blessed(1);
    print  $JSON->encode($namegen);

}elsif (defined $q->param('type') and $q->param('type') eq 'dump' ){
    print $q->header( 'text/plain' );
    print Dumper $namegen;
}else {
    print $q->header;
    print print_page($testcityid,$namegen);
}

exit;

#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

sub print_page {
    my ($testcityid,$namegen)=@_;
    my $qstring=$ENV{'QUERY_STRING'};
    $qstring.="&seed=".$testcityid   if (! defined $q->param('seed'));


    my $templates = Template->new({
        INCLUDE_PATH => 'Templates/',
        INTERPOLATE  => 1,
    }) || die "$Template::ERROR\n";

    my $formtmpl;
    my $vars = {    
        'races'         =>  NPCGenerator::get_races() ,
        'selectedrace'  =>  $q->param('race'), ,
        'names'         =>  $namegen,
    };
    $templates->process('nameform.tmpl', $vars, \$formtmpl) || die $templates->error(), "\n";

    $vars = {
        'title'        => 'Name Generator',
        'subheader'        => 'set <a href="/namegenerator?'.$qstring.'">'.$testcityid.'</a>',
        'content'       => $formtmpl,
    };
    $templates->process('base.tmpl', $vars) || die $templates->error(), "\n";
}



