#!/usr/bin/perl -wT

use strict;
use warnings;
use CGI;
use Data::Dumper;
use JSON;
use List::Util 'shuffle', 'min', 'max' ;
use POSIX;
use Template;
use XML::Simple;
use lib "lib/";
use GenericGenerator;
use NPCGenerator;
use NPCFormatter;
our $q = CGI->new;


    my $npc_presets=parse_presets($q);

my $npc=NPCGenerator::create($npc_presets);



if (defined $q->param('type') and $q->param('type') eq 'xml' ){
    print $q->header( 'text/xml' );
    print "<?xml version='1.0'  encoding='utf-8' ?>\n";
    print XMLout($npc);

} elsif (defined $q->param('type') and $q->param('type') eq 'json' ){
    print $q->header( 'application/json' );
    my $JSON  = JSON->new->utf8;
    $JSON->convert_blessed(1);
    print $JSON->encode($npc);

} elsif (defined $q->param('type') and $q->param('type') eq 'dump' ){
    print $q->header( 'text/plain' );
    print Dumper $npc;

} else {
    print $q->header( 'text/html; charset=utf-8' );
    print_page($npc);
}

exit;

#################################################################################################
#################################################################################################
#################################################################################################
sub parse_presets {
    my ($q)=@_;
    my $presets;
    $presets->{'seed'}          = $1 if ( defined $q->param('seed')         and $q->param('seed')       =~ /^(\d+)$/x );
    $presets->{'race'}          = $1 if ( defined $q->param('race')         and $q->param('race')       =~ /^([a-z\-]+)$/x );
    $presets->{'sex'}           = $1 if ( defined $q->param('sex')          and $q->param('sex')       =~ /^([a-z\-]+)$/x );
    $presets->{'class'}         = $1 if ( defined $q->param('class')        and $q->param('class')      =~ /^([a-z\- ]+)$/x );
    $presets->{'profession'}    = $1 if ( defined $q->param('profession')   and $q->param('profession') =~ /^([a-z\- ]+)$/x );
    $presets->{'business'}      = $1 if ( defined $q->param('business')     and $q->param('business')   =~ /^([a-z\- ]+)$/x );
    $presets->{'title'}         = $1 if ( defined $q->param('title')        and $q->param('title')      =~ /^([a-z\- ]+)$/x );

    foreach my $climatestat ( ('altitude', 'continentality', 'latitude', 'pressure', 'temperature', 'precipitation' ) ){
        $presets->{'climate'}->{'stats'}->{$climatestat} = $1 if ( defined $q->param($climatestat)     and $q->param("climate_".$climatestat)       =~/^(\d+)$/x );
    }

    return $presets;

}

sub print_page {
    my ($npc)=@_;

    my $templates = Template->new({
        INCLUDE_PATH => 'Templates/',
        INTERPOLATE  => 1,
    }) || die "$Template::ERROR\n";
    my $vars = {
        'title'         => 'Meet '.$npc->{'name'}."! (<a href='/npcgenerator?seed=$npc->{'seed'}' >$npc->{'seed'}</a>)",
        'seed'          => $npc->{'seed'},
        'content'       => print_content($npc),
    };
    return $templates->process('base.tmpl', $vars) || die $templates->error(), "\n";
}

sub print_content {
    my ($npc)=@_;

    my $templates = Template->new({
        INCLUDE_PATH => 'Templates/',
        INTERPOLATE  => 1,
    }) || die "$Template::ERROR\n";

    my $formtmpl;
    my $vars = {
        'npcname'             => $npc->{'name'},
            'seed'            => $npc->{'seed'},
            'summarytext'     => NPCFormatter::printSummary($npc),
            'descriptiontext' => NPCFormatter::printDescription($npc),
            'npcdatatext'     => NPCFormatter::printData($npc),
    };
    $templates->process('npcgenerator_content.tmpl', $vars, \$formtmpl) || die $templates->error(), "\n";

    return $formtmpl;
}

__END__


=head1 AUTHOR

Jesse Morgan (morgajel)  C<< <morgajel@gmail.com> >>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2013, Jesse Morgan (morgajel) C<< <morgajel@gmail.com> >>. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation version 2
of the License.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

=head1 DISCLAIMER OF WARRANTY

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut
